#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: besu-errorprone-checks
  description: Besu
  homepage: https://wiki.hyperledger.org/display/besu
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
