name: CI Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OIDC_PROVIDER: 'besu-errorprone'

    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JFrog CLI with OIDC
        id: setup-jfrog-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to JFrog Artifactory
        run: ./gradlew artifactoryPublish
        env:
          ARTIFACTORY_USER: ${{ steps.setup-jfrog-cli.outputs.oidc-user }}
          ARTIFACTORY_KEY: ${{ steps.setup-jfrog-cli.outputs.oidc-token }}